import frappe
def get_property_setters():
    return [
        {
            "doctype": "HD Ticket",
            "fieldname": "custom_logged_time",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "subject",
            "property": "allow_in_quick_entry",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "contact",
            "property": "label",
            "value": "Logged By",
            "property_type": "Data",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "description",
            "property": "reqd",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "custom_resolution_sla_breach",
            "property": "in_list_view",
            "value": "0",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "custom_response_sla_breach",
            "property": "in_list_view",
            "value": "0",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "priority",
            "property": "default",
            "value": "Medium",
            "property_type": "Text",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "customer",
            "property": "fetch_from",
            "value": "",
            "property_type": "Small Text",
        },
        
       
        {
            "doctype": "HD Ticket",
            "fieldname": "is_merged",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "ticket_split_from",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "total_hold_time",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "user_resolution_time",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "via_customer_portal",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "workflow_state",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
      
        {
            "doctype": "HD Ticket",
            "fieldname": "email_account",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "feedback_rating",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "custom_priorityy",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "custom_pending_reason",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "opening_time",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "opening_date",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "on_hold_since",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "merged_with",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "key",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "custom_impact",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "first_response_time",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "first_responded_on",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "feedback",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "feedback_extra",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "custom_solution",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },

        {
            "doctype": "HD Ticket",
            "fieldname": "agreement_status",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "service_level_agreement_creation",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "sla",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "custom_service_window",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "custom_schedule_date",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "description",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "customer",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "content_type",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "contact",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "custom_closure_code",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "custom_closure_category",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "ticket_type",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "custom_classification_category",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "custom_cancellation_remarks",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "custom_cancel_edit_used",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "avg_response_time",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "resolution_details",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "resolution_date",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "custom_resolution_code",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "amended_from",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "raised_by",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "priority",
            "property": "reqd",
            "value": "0",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "ticket_type",
            "property": "label",
            "value": "Classification",
            "property_type": "Data",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "subject_section",
            "property": "label",
            "value": "",
            "property_type": "Data",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "priority",
            "property": "label",
            "value": "",
            "property_type": "Data",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "response_by",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "resolution_by",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "resolution_time",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "priority",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "status",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "subject",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "key",
            "property": "hidden",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "template",
            "property": "hidden",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "summary",
            "property": "hidden",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "subject",
            "property": "depends_on",
            "value": "",
            "property_type": "Data",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "subject",
            "property": "mandatory_depends_on",
            "value": "",
            "property_type": "Data",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "status",
            "property": "in_standard_filter",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "description",
            "property": "depends_on",
            "value": "",
            "property_type": "Data",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "description",
            "property": "mandatory_depends_on",
            "value": "",
            "property_type": "Data",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "description",
            "property": "allow_in_quick_entry",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "raised_by",
            "property": "hidden",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "ticket_type",
            "property": "allow_in_quick_entry",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "ticket_type",
            "property": "depends_on",
            "value": 'eval:doc.custom_entry_type == "Incident"',
            "property_type": "Data",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "custom_entry_type",
            "property": "in_list_view",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "status",
            "property": "read_only",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "status_category",
            "property": "in_standard_filter",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "subject",
            "property": "read_only",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "email_account",
            "property": "reqd",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "email_account",
            "property": "fetch_if_empty",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "email_account",
            "property": "fetch_from",
            "value": "custom_workgroup.team_name",
            "property_type": "Small Text",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "description",
            "property": "read_only",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "sla",
            "property": "read_only",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "first_responded_on",
            "property": "read_only",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "meta_tab",
            "property": "hidden",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "feedback_tab",
            "property": "hidden",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "email_account",
            "property": "label",
            "value": "Workgroup",
            "property_type": "Data",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "contact",
            "property": "read_only",
            "value": "1",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "custom_assigned_to",
            "property": "in_list_view",
            "value": "0",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": None,
            "property": "title_field",
            "doctype_or_field":"DocType",
            "property_type": "Data",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "sla_tab",
            "property": "depends_on",
            "value": "",
            "property_type": "Data",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "ticket_type",
            "property": "mandatory_depends_on",
            "value": 'eval:doc.custom_entry_type == "Incident"',
            "property_type": "Data",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "subject",
            "property": "length",
            "value": "500",
            "property_type": "Int",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "subject",
            "property": "permlevel",
            "value": "0",
            "property_type": "Int",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "status",
            "property": "no_copy",
            "value": "0",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "custom_actual_effortss",
            "property": "in_list_view",
            "value": "0",
            "property_type": "Check",
        },
        {
            "doctype": "HD Ticket",
            "fieldname": "ticket_type",
            "property": "reqd",
            "value": "1",
            "property_type": "Check",
        }

    ]
    


def create_property_setters():
    for ps in get_property_setters():

        frappe.make_property_setter(
            ps,
            validate_fields_for_doctype=False
        )